"""making the option (text) not-null lable in options table

Revision ID: 126c47245b17
Revises: 8bccfb56d436
Create Date: 2024-12-11 08:16:53.729670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126c47245b17'
down_revision = '8bccfb56d436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
