"""removing the not null attrepute from option (text) in options table

Revision ID: 36a0643ff9ab
Revises: e7ac2ac8e6f5
Create Date: 2024-12-11 01:46:57.003455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a0643ff9ab'
down_revision = 'e7ac2ac8e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
