"""adding type column in the questions table

Revision ID: 3ec4cefa058d
Revises: aa2b6b42b206
Create Date: 2024-09-17 13:03:15.051550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec4cefa058d'
down_revision = 'aa2b6b42b206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=5), nullable=False))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
