"""Changing 'name' in tests table to 'title'

Revision ID: 86a52466211d
Revises: 3ec4cefa058d
Create Date: 2024-12-10 22:53:41.824280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a52466211d'
down_revision = '3ec4cefa058d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, server_default='Default Title'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, server_default='Default Title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
