"""adding multiple_sections, one_section_per_page, correction_type columns to tests table

Revision ID: cad2a0af3145
Revises: 0be5e945b543
Create Date: 2024-12-11 12:01:26.572885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad2a0af3145'
down_revision = '0be5e945b543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiple_sections', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('one_section_per_page', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('correction_type', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('correction_type')
        batch_op.drop_column('one_section_per_page')
        batch_op.drop_column('multiple_sections')

    # ### end Alembic commands ###
