"""changing the 'category' column in the tests table to 'type'

Revision ID: e7ac2ac8e6f5
Revises: cbb9e0a215f6
Create Date: 2024-12-11 00:30:37.916310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ac2ac8e6f5'
down_revision = 'cbb9e0a215f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
