"""coverting the passhash table form TEXT to VARCHAR(255)

Revision ID: f2e612c1f8e0
Revises: f883fc236383
Create Date: 2024-07-21 23:33:33.657001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e612c1f8e0'
down_revision = 'f883fc236383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('passhash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('passhash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
